/**:
  ros__parameters:
    'goal_tolerance': 0.2
    'continuous_model_path': 'vehicles/hardware/dji/dji_captain/models/M350/continuous_model/model_bla_diag_cmdvle.npz'
    'discrete_model_path': 'vehicles/hardware/dji/dji_captain/models/M350/discrete_model/discrete_models.yaml'
    'rope_length': 10.0
    'xi': 0.1
    'max_speed': 1.0
    'max_acceleration': 2.0
    'sattle_extra': 20.0